### ISSUE TITLE
TODO List - 1.0.0

### ISSUE THREAD

**Issue by Sandertv** [BlockHorizons/BlockPets#1]
**TODO List for the 1.0.0 release**

**AI Improvements**
- [x] Fix jumping not properly working.
- [x] Add jumping pets AI.
- [x] Add swimming pets AI.
- [x] Arrow controlled pets when riding.

**Commands**
- [x] Fix/add levelup pet command.
- [x] Add healpet command.

**Features**
- [x] Add pet leveling up mechanics, including level points.
- [x] Add fighting pets if owner gets attacked or starts attacking. Levels up this way.
- [x] Experience system, experience is obtained if the pet kills something, or **somebody**.
- [x] Pet inventories, adding the possibility to store items and get them out again.
- [x] Indirect following of pets, with the pets moving around some more.
- [x] Fully configurable pet properties, like speed, jumping height, flying height, rideable etc...
- [x] Putting pets on your head.

**Database**
- [x] Pets Database support, MySQL and SQLite.
- [x] Pet storing.
- [x] Pet reconstructing.
- [x] Pet updating.

**Other bug fixes**
- [ ] Fix horses and pigs freezing your game when riding them. (edit: And Llamas)
- [ ] Fix spawnpet command without dot not working. (Server software issue!)
- [x] Clean up code a lot.
- [x] Fix pets still being 'mounted' while already unmounted.
- [x] |-> Fix pets spinning around in circles as a result of this workaround.
- [x] Fix pets duplicating silently when dying.

**Configuration**
- [x] Add a configuration file.
- [x] Make pet damaging configurable. (?)
- [x] Make fighting pets configurable. (once implemented)
- [x] Make more things configurable.
- [x] Configurable messages (#43)

**Developer API**
- [x] Add a bunch of events to change behaviour of BlockPets.
- [x] Document all functions very clearly so they can be easily used.

**Testing required**
- [x] Level change teleporting.
- [x] Basically the whole plugin.

TODO list done? Plugin nice?
- [x] Move it to BlockHorizons organization.

Edit: Moved Economy integration to the next release. First release will be about implementing the big features and getting everything working.

**Comment by SerezhaIvanov** [comment]
Add please block pet

**Comment by Sandertv** [comment]
I might add it later, but it requires too many changes to make it working properly, even a complete extra argument just for one pet.

**Comment by brianzp** [comment]
Hi. I didn't feel like creating another issue as it would waste a ticket so just wanted to say Thank You for this super awesome and working plugin. :)

**Comment by Sandertv** [comment]
I'm very glad you like the plugin! If there's anything you would like to see before the initial release, please make sure to tell me :)

**Comment by LordJoshie** [comment]
this will be complex, maybe... 

but perhaps owner control over their pet, such as whether or not to have it fight. like /petpvp (name) (on/off) 
or maybe to turn off your pet temporarily... and summon it back out easily with a command /pet (name) on/off 

I think these would make the use of the pet much better not only for server owners, but the players also. 

since if a pet is summoned, it's using resources on the server... but if the player has no need for their pet to be out for anything, then it would be ideal to be able to turn your pet off, without despawning it. 

also, when you add the inventories thing... perhaps an option where your pet can automatically pickup drops for you, while mining, or during pvp, if someone drops something, the pet can collect it for you. 

I think these additional features would make the plugin more useful. fornow tho, it's amazing for what it is !

**Comment by Sandertv** [comment]
For the first option, I could add that later, for now there's only a global setting to change that in the config.yml. For the second one, you can use /togglepets to toggle your pets on/off.

The third idea, I really like that idea. I'll definitely see if I can implement that together with @Muqsit and see if we can get that working.

**Comment by LordJoshie** [comment]
Okay, awesome !

I didn't know about the toggle pets. 

all the commands for the pets aren't under one command, so it's hard to know them all without lookin at the Plugin.yml

**Comment by Sandertv** [comment]
I'll be adding a /pet command with /pet help and /pet reload, so you can find out easier. I'll also add a wiki later, but for now I'll first finish the plugin.

**Comment by LordJoshie** [comment]
I just checked, and don't have a togglepet command xD

**Comment by Sandertv** [comment]
Try togglepet**s** 😄 
There should be /pet help in newer commits, so that should make things easier for you too.

**Comment by LordJoshie** [comment]
Wait wait... xD 

I just updated to the latest release, and notice that the toggle pets works. 

However, is there a way to do it like /togglepet (portion of the name) to toggle just that one pet ? 

Also, perhaps the ability to set permissions for more than 2 pets for specific people, or if that's already a possibility...then can you let me know ?

**Comment by LordJoshie** [comment]
Another suggestion ! 

to help level up a pet, in a passive way, by not killing a player... 

perhaps you could make it so you need to have a type of item on you, to exchange to feed your pet, and the more you exchange your items to heal/feed the pet, it's experience towards a higher level can go up a bit 

Say if you have a pet whose health is 6/20, it will take 14 carrots to heal your pet, and it will give it 7% experience towards a new level. 

if your pet doesn't need to eat, it will cancel taking the carrots and tell you that your pet isn't hungry, to prevent people from using that as an exploit to level their pets up super quick. 

I really love this plugin, and if it's made better in any way with these suggestions then great ! 
but I know coding is complex, and some of these ideas may be too difficult to incorporate. 

Thanks !

**Comment by Sandertv** [comment]
Added per-pet toggling, will add per-player limit, and added leveling up by feeding the pet. It now has a scaling of: {foodpoints} / 20 * {petLevel} + 2. So that would mean for example when I'm feeding steak, and say my pet is level 10: 8 / 20 * 10 + 2 = 6 experience points.

**Comment by LordJoshie** [comment]
Can you contact me by email, I have a proposal for some plugin requests I think you'd be able to handle. 

jawshawa.p@gmail.com

**Comment by Muqsit** [comment]
@Sandertv I am getting busier and busier every day. I don't think I can create a common bridge any time soon. If you want to, you may create a PR for PlayerVaults regarding BlockPets. I won't be be getting any time till 9th of next month.

**Comment by Sandertv** [comment]
That's perfectly fine @Muqsit, I'll look into PlayerVaults and see if I can figure out a good way, glad you told me. 😄

**Comment by jasonwynn10** [comment]
The lit is almost done! 😄

**Comment by Sandertv** [comment]
Yap 😄

**Comment by Sandertv** [comment]
Plugin has been released on Poggit. Wooo! Time to close this.

**Comment by Sandertv** [comment]
Plugin has been released on Poggit. Wooo! Time to close this.

**Comment by Driesboy** [comment]
nice duplicate :)

**Comment by Sandertv** [comment]
Duplicate? What do you mean?

**Comment by Driesboy** [comment]
your message

**Comment by Driesboy** [comment]
![naamloos](https://user-images.githubusercontent.com/15795262/28240459-971f04a2-6982-11e7-830d-60ec8f26aa32.jpeg)

**Comment by Sandertv** [comment]
Oh, that was probably because of bad internet connection. 😅
